// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNem4V8YrzSYDPSNFG1efkG-Eg4NF21WI',
    appId: '1:1014239916524:web:3a21f3d9e64bdeea55d0c9',
    messagingSenderId: '1014239916524',
    projectId: 'chattingapp-eabb5',
    authDomain: 'chattingapp-eabb5.firebaseapp.com',
    storageBucket: 'chattingapp-eabb5.appspot.com',
    measurementId: 'G-KEP67C9S7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQRNGBF-cNM5tqrqQb6XGDImcoC3lrfxs',
    appId: '1:1014239916524:android:b4dd10437ad2bcf655d0c9',
    messagingSenderId: '1014239916524',
    projectId: 'chattingapp-eabb5',
    storageBucket: 'chattingapp-eabb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANsvuaf17IijDIe4avxT6mMiRYu2EWMCg',
    appId: '1:1014239916524:ios:7fa622439745d0ec55d0c9',
    messagingSenderId: '1014239916524',
    projectId: 'chattingapp-eabb5',
    storageBucket: 'chattingapp-eabb5.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANsvuaf17IijDIe4avxT6mMiRYu2EWMCg',
    appId: '1:1014239916524:ios:7fa622439745d0ec55d0c9',
    messagingSenderId: '1014239916524',
    projectId: 'chattingapp-eabb5',
    storageBucket: 'chattingapp-eabb5.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNem4V8YrzSYDPSNFG1efkG-Eg4NF21WI',
    appId: '1:1014239916524:web:31a9264497c71efc55d0c9',
    messagingSenderId: '1014239916524',
    projectId: 'chattingapp-eabb5',
    authDomain: 'chattingapp-eabb5.firebaseapp.com',
    storageBucket: 'chattingapp-eabb5.appspot.com',
    measurementId: 'G-4QE33E2TS1',
  );

}